server:
  port: 9002
spring:
  application:
    name: microservice-movie #服务名称
eureka:
  client:
    register-with-eureka: true #作为客户端需要注册到Eureka
    fetch-registry: true #作为客户端需要从Eureka获取注册信息
    service-url: #客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka,http://127.0.0.1:9999/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #优先使用该服务的IP地址注册到Eureka
feign:
  hystrix:
    enabled: true